---
- name: "Finalize playbook | {{ _title_pfx }}"
  delegate_to: "{{ jenkins__delegate_to }}"
  tags: [always, finalize]
  block:

  - name: "Clean tmp files and directories | finish | {{ _title_pfx }}"
    ansible.builtin.file:
      path: "{{ jenkins__tmp_dir }}"
      state: absent
