---
- name: "Playbook for deploy Jenkins | {{ _title_pfx }}"
  delegate_to: "{{ jenkins__delegate_to }}"
  block:

    - name: "Initialize playbook | {{ _title_pfx }}"
      ansible.builtin.import_tasks:
        file: init.yml
      tags: [always, initialize]

    - name: "Install Jenkins server | {{ _title_pfx }}"
      ansible.builtin.import_tasks:
        file: install.yml
      tags: [install]

    - name: "Remove Jenkins server | {{ _title_pfx }}"
      ansible.builtin.import_tasks:
        file: remove.yml
      tags: [never, remove]

    - name: "Finalize playbook | {{ _title_pfx }}"
      ansible.builtin.import_tasks:
        file: finish.yml
      tags: [always, finalize]
